export {
  BOARD_SIZE,
  DICE_ANIMATION_MS,
  DISCONNECT_FORFEIT_MS,
  EMPTY_ROOM_TTL_MS,
  GAME_OVER_TTL_MS,
  MAX_CONSECUTIVE_AFK_TURNS,
  MAX_ROOMS,
  NICKNAME_MAX_LENGTH,
  PLACEMENT_TIME_LIMIT_MS,
  PROTOCOL_VERSION,
  RATE_LIMIT_EVENTS_PER_SECOND,
  ROOM_ID_ALPHABET,
  ROOM_ID_LENGTH,
  SESSION_STORE_TTL_MS,
  START_COUNTDOWN_MS,
} from './constants.js';
export { randomTargets, resolveTurn, shotsAllowed, TARGET_VIOLATIONS, validateTargets } from './engine.js';
export type {
  Battle,
  Board,
  InvalidTargets,
  ResolvedTurn,
  TargetValidation,
  TargetViolation,
  TurnResolution,
  ValidTargets,
} from './engine.js';
export {
  completeFleet,
  generateRandomFleet,
  PLACEMENT_VIOLATIONS,
  toPlacedShip,
  validateDraft,
  validateFleet,
} from './placement.js';
export type { InvalidPlacement, PlacementValidation, PlacementViolation, ValidPlacement } from './placement.js';
export { CLIENT_EVENTS, ERROR_CODES, SERVER_EVENTS } from './protocol.js';
export type {
  Ack,
  AckFailure,
  AckResponse,
  AckSuccess,
  BattleSnapshot,
  ClientToServerEvents,
  CommandEvent,
  CommandPayload,
  ConfirmRulesPayload,
  CreateRoomPayload,
  DiceRoll,
  DiceRolledPayload,
  EchoResponse,
  EmptyPayload,
  ErrorCode,
  GameOverSnapshot,
  HandshakeAuth,
  HealthResponse,
  JoinRoomAckData,
  JoinRoomPayload,
  PerPlayer,
  PlacementSnapshot,
  PlayerStateSnapshot,
  PlayerView,
  RematchChoicePayload,
  ServerToClientEvents,
  SessionCredentials,
  SetPausedPayload,
  ShotResolvedPayload,
  TargetsPayload,
  UpdatePlacementPayload,
  UpdateRulesAckData,
  UpdateRulesPayload,
} from './protocol.js';
export { createCryptoRng, createSeededRng } from './random.js';
export type { Rng } from './random.js';
export { DEFAULT_RULES } from './rules.js';
export {
  FLEET,
  GAME_OVER_REASONS,
  ORIENTATIONS,
  REMATCH_CHOICES,
  ROOM_PHASES,
  SEATS,
  SHIP_LENGTH,
  SHIP_TYPES,
  SHOT_OUTCOMES,
  TIMEOUT_ACTIONS,
} from './types.js';
export type {
  Coordinate,
  GameOverReason,
  GameRules,
  Orientation,
  PlacedShip,
  RematchChoice,
  RoomPhase,
  Seat,
  ShipPlacement,
  ShipType,
  ShotOutcome,
  ShotResult,
  TimeoutAction,
  TurnTimeLimitSeconds,
} from './types.js';
export { isRoomId, parseNickname, PAYLOAD_PARSERS, parseSessionCredentials } from './validation.js';
export type { PayloadParser } from './validation.js';
