// Room logic as a pure transition function (docs/server.md#room-state-machine, ADR-0037): no timers, sockets or I/O.

import {
  CLIENT_EVENTS,
  DEFAULT_RULES,
  ERROR_CODES,
  GAME_OVER_REASONS,
  PLACEMENT_TIME_LIMIT_MS,
  resolveTurn,
  ROOM_PHASES,
  SEATS,
  SERVER_EVENTS,
  shotsAllowed,
  TARGET_VIOLATIONS,
  validateDraft,
  validateFleet,
  validateTargets,
  type Battle,
  type CommandPayload,
  type Coordinate,
  type ErrorCode,
  type GameRules,
  type JoinRoomPayload,
  type PlacedShip,
  type PlacementViolation,
  type Seat,
  type ShotResolvedPayload,
  type TargetViolation,
} from '@battleship/core';

/** A seated player as the server knows them; the secret never leaves the server except in the player's own ack. */
export interface RoomPlayer {
  /** Trimmed by the `CREATE_ROOM` / `JOIN_ROOM` guard. */
  readonly nickname: string;
  /** The seat's credential (docs/server.md#sessions--reconnection), generated by the caller, not by room logic. */
  readonly playerSecret: string;
}

/** One player's fleet during `PLACEMENT` (ADR-0005). */
export interface PlacementFleet {
  /** The latest draft that passed `validateDraft`, with derived coordinates; empty until the first update. */
  readonly ships: readonly PlacedShip[];
  /** Whether the player locked the fleet with `CONFIRM_PLACEMENT`; only a complete fleet can be locked. */
  readonly hasConfirmed: boolean;
}

/** What every phase of a room carries. */
interface RoomBase {
  /** `ROOM_ID_LENGTH` characters of `ROOM_ID_ALPHABET`, unique among the open rooms. */
  readonly roomId: string;
  /** The rules the match is played with; `DEFAULT_RULES` until rules negotiation lands (#26). */
  readonly rules: GameRules;
  /** Bumped by every `UPDATE_RULES` once negotiation lands (#26); `0` until then. */
  readonly rulesVersion: number;
}

/** A room with only its creator seated. */
export interface WaitingRoom extends RoomBase {
  /** Discriminant. */
  readonly phase: typeof ROOM_PHASES.WAITING_FOR_OPPONENT;
  /** `P2` is empty until `JOIN_ROOM`. */
  readonly players: { readonly P1: RoomPlayer; readonly P2: null };
}

/** A room where both players place their fleets. */
export interface PlacementRoom extends RoomBase {
  /** Discriminant. */
  readonly phase: typeof ROOM_PHASES.PLACEMENT;
  /** Both seats are taken from here on. */
  readonly players: Readonly<Record<Seat, RoomPlayer>>;
  /** Each seat's draft or locked fleet. */
  readonly fleets: Readonly<Record<Seat, PlacementFleet>>;
  /**
   * When unconfirmed fleets will be completed and locked, in epoch ms: `PLACEMENT_TIME_LIMIT_MS` after phase entry.
   * Only projected as `remainingMs` until the placement timer enforces it (#28).
   */
  readonly deadline: number;
}

/** A room whose match is being played. */
export interface BattleRoom extends RoomBase {
  /** Discriminant. */
  readonly phase: typeof ROOM_PHASES.IN_PROGRESS;
  /** Both seats are taken. */
  readonly players: Readonly<Record<Seat, RoomPlayer>>;
  /** Boards and turn, as `resolveTurn` returns them (ADR-0033). */
  readonly battle: Battle;
  /** The current turn's draft from `UPDATE_TARGETS`; cleared whenever the turn is fired. */
  readonly draftTargets: readonly Coordinate[];
}

/** A room whose match has ended. */
export interface GameOverRoom extends RoomBase {
  /** Discriminant. */
  readonly phase: typeof ROOM_PHASES.GAME_OVER;
  /** Both seats are taken. */
  readonly players: Readonly<Record<Seat, RoomPlayer>>;
  /** The final boards; both fleets are revealed from here on. */
  readonly battle: Battle;
  /** The seat that sank the opponent's last ship. */
  readonly winner: Seat;
  /** How the match ended; only `FLEET_DESTROYED` until surrender (#35), AFK (#30) and forfeit (#23) land. */
  readonly reason: typeof GAME_OVER_REASONS.FLEET_DESTROYED;
}

/**
 * Everything the server keeps about one room, one variant per phase it can be in (ADR-0037). `RULES_NEGOTIATION`
 * joins with #26; until then `JOIN_ROOM` goes straight to `PLACEMENT` with the default rules.
 */
export type RoomState = WaitingRoom | PlacementRoom | BattleRoom | GameOverRoom;

/** Commands a seated player sends, handled by `applyCommand`. */
type SeatCommandEvent =
  | typeof CLIENT_EVENTS.UPDATE_PLACEMENT
  | typeof CLIENT_EVENTS.CONFIRM_PLACEMENT
  | typeof CLIENT_EVENTS.UNLOCK_PLACEMENT
  | typeof CLIENT_EVENTS.UPDATE_TARGETS
  | typeof CLIENT_EVENTS.FIRE;

/** The placement commands, handled by `applyPlacementCommand`. */
type PlacementCommandEvent =
  | typeof CLIENT_EVENTS.UPDATE_PLACEMENT
  | typeof CLIENT_EVENTS.CONFIRM_PLACEMENT
  | typeof CLIENT_EVENTS.UNLOCK_PLACEMENT;

/** The turn commands, handled by `applyBattleCommand`. */
type BattleCommandEvent = typeof CLIENT_EVENTS.UPDATE_TARGETS | typeof CLIENT_EVENTS.FIRE;

/**
 * A command from a seated player: the event, the sender's seat (the caller maps the socket to it) and the payload
 * as its core guard returned it (ADR-0031).
 */
export type SeatCommand = {
  [E in SeatCommandEvent]: {
    /** The protocol event. */
    readonly type: E;
    /** The sender. */
    readonly seat: Seat;
    /** The guard's normalized copy of the payload. */
    readonly payload: CommandPayload<E>;
  };
}[SeatCommandEvent];

/** `JOIN_ROOM`, which comes from a player without a seat yet. */
export interface JoinRoomCommand {
  /** The protocol event. */
  readonly type: typeof CLIENT_EVENTS.JOIN_ROOM;
  /** The guard's normalized copy of the payload; the caller already used `roomId` to find the room. */
  readonly payload: JoinRoomPayload;
  /** The joiner's new secret, generated by the caller, which also returns it in the ack. */
  readonly playerSecret: string;
}

/** Every command `applyCommand` handles; `CREATE_ROOM` builds a room with `createRoom` instead. */
export type RoomCommand = JoinRoomCommand | SeatCommand;

/**
 * Something the caller must do besides sending `STATE`, which it sends to every seated player after any accepted
 * command (ADR-0037). Timer scheduling (#28, #30) and `DICE_ROLLED` (#29) will join this union.
 */
export interface ShotResolvedEffect {
  /** Discriminant, named after the event to emit to both players. */
  readonly type: typeof SERVER_EVENTS.SHOT_RESOLVED;
  /** The event payload, for animation and sound. */
  readonly payload: ShotResolvedPayload;
}

/** What the caller must do after an accepted command, besides sending `STATE`. */
export type RoomEffect = ShotResolvedEffect;

/** An accepted command. */
export interface AcceptedTransition {
  /** Discriminant. */
  readonly ok: true;
  /** The room after the command; the same object when the command changed nothing (a repeated confirm or unlock). */
  readonly state: RoomState;
  /** In the order the caller must perform them. */
  readonly effects: readonly RoomEffect[];
}

/** A refused command: the room is left as it was, and `error` goes back in the ack. */
export interface RejectedTransition {
  /** Discriminant. */
  readonly ok: false;
  /** What the ack reports (docs/protocol.md#error-codes). */
  readonly error: ErrorCode;
  /** For `INVALID_PLACEMENT` and `INVALID_TARGETS`, the rule broken; for the server log only, never sent (ADR-0032). */
  readonly violation?: PlacementViolation | TargetViolation;
}

/** Outcome of `applyCommand`. */
export type TransitionResult = AcceptedTransition | RejectedTransition;

/** A placement fleet before the player's first update. */
const EMPTY_FLEET: PlacementFleet = { ships: [], hasConfirmed: false };

/** The seat that starts every match until the dice roll lands (#29). */
const FIRST_SEAT: Seat = SEATS.P1;

/**
 * Opens a room in `WAITING_FOR_OPPONENT` with `DEFAULT_RULES` and seats the creator as `P1` (`CREATE_ROOM`).
 * @param roomId A fresh id, unique among the open rooms; the caller generates it.
 * @param creator The creator's nickname, as the guard returned it, and their new secret.
 * @returns The new room.
 */
export function createRoom(roomId: string, creator: RoomPlayer): WaitingRoom {
  return {
    phase: ROOM_PHASES.WAITING_FOR_OPPONENT,
    roomId,
    rules: DEFAULT_RULES,
    rulesVersion: 0,
    players: { P1: creator, P2: null },
  };
}

/**
 * Applies one command to a room (docs/server.md#transition-rules). Pure: the input is never mutated, and a refused
 * command returns no state, so the caller keeps the room it had.
 * @param state The room before the command.
 * @param command The command, with a payload that already passed its guard.
 * @param now Current time in epoch ms; deadlines are stored as timestamps and projected as remaining time.
 * @returns The new room and the effects to perform, or the error for the ack.
 */
export function applyCommand(state: RoomState, command: RoomCommand, now: number): TransitionResult {
  switch (command.type) {
    case CLIENT_EVENTS.JOIN_ROOM:
      return joinRoom(state, command, now);
    case CLIENT_EVENTS.UPDATE_PLACEMENT:
    case CLIENT_EVENTS.CONFIRM_PLACEMENT:
    case CLIENT_EVENTS.UNLOCK_PLACEMENT:
      return state.phase === ROOM_PHASES.PLACEMENT
        ? applyPlacementCommand(state, command)
        : reject(ERROR_CODES.WRONG_PHASE);
    case CLIENT_EVENTS.UPDATE_TARGETS:
    case CLIENT_EVENTS.FIRE:
      return state.phase === ROOM_PHASES.IN_PROGRESS
        ? applyBattleCommand(state, command)
        : reject(ERROR_CODES.WRONG_PHASE);
  }
}

/**
 * Seats the joiner as `P2` and starts placement. A room with both seats taken is `ROOM_FULL` in every phase, so
 * `JOIN_ROOM` never answers `WRONG_PHASE`.
 * @param state The room.
 * @param command The join, with the joiner's nickname and secret.
 * @param now Current time in epoch ms; the placement deadline counts from it.
 * @returns The room in `PLACEMENT`, or `ROOM_FULL`.
 */
function joinRoom(state: RoomState, command: JoinRoomCommand, now: number): TransitionResult {
  if (state.phase !== ROOM_PHASES.WAITING_FOR_OPPONENT) {
    return reject(ERROR_CODES.ROOM_FULL);
  }
  const joiner: RoomPlayer = { nickname: command.payload.nickname, playerSecret: command.playerSecret };
  return accept({
    phase: ROOM_PHASES.PLACEMENT,
    roomId: state.roomId,
    rules: state.rules,
    rulesVersion: state.rulesVersion,
    players: { P1: state.players.P1, P2: joiner },
    fleets: { P1: EMPTY_FLEET, P2: EMPTY_FLEET },
    deadline: now + PLACEMENT_TIME_LIMIT_MS,
  });
}

/**
 * Handles the placement commands (docs/server.md#placement): draft updates, confirmation and unlock. The second
 * confirmation starts the match at once, `P1` first; the start countdown (#28) and the dice roll (#29) come later.
 * @param state The room in `PLACEMENT`.
 * @param command A placement command.
 * @returns The updated room, or the error for the ack.
 */
function applyPlacementCommand(
  state: PlacementRoom,
  command: Extract<SeatCommand, { type: PlacementCommandEvent }>,
): TransitionResult {
  const fleet = state.fleets[command.seat];
  switch (command.type) {
    case CLIENT_EVENTS.UPDATE_PLACEMENT: {
      if (fleet.hasConfirmed) {
        return reject(ERROR_CODES.PLACEMENT_LOCKED);
      }
      const validation = validateDraft(command.payload.ships, state.rules);
      if (!validation.ok) {
        return reject(ERROR_CODES.INVALID_PLACEMENT, validation.reason);
      }
      return accept(withFleet(state, command.seat, { ships: validation.ships, hasConfirmed: false }));
    }
    case CLIENT_EVENTS.CONFIRM_PLACEMENT: {
      if (fleet.hasConfirmed) {
        return accept(state);
      }
      const validation = validateFleet(fleet.ships, state.rules);
      if (!validation.ok) {
        return reject(ERROR_CODES.INVALID_PLACEMENT, validation.reason);
      }
      const next = withFleet(state, command.seat, { ships: fleet.ships, hasConfirmed: true });
      return accept(next.fleets.P1.hasConfirmed && next.fleets.P2.hasConfirmed ? startBattle(next) : next);
    }
    case CLIENT_EVENTS.UNLOCK_PLACEMENT:
      return accept(
        fleet.hasConfirmed ? withFleet(state, command.seat, { ships: fleet.ships, hasConfirmed: false }) : state,
      );
  }
}

/**
 * Handles the turn commands (docs/server.md#turns): the active player's draft and the shot itself.
 * @param state The room in `IN_PROGRESS`.
 * @param command `UPDATE_TARGETS` or `FIRE`.
 * @returns The updated room with `SHOT_RESOLVED` after a fired turn, or the error for the ack.
 */
function applyBattleCommand(
  state: BattleRoom,
  command: Extract<SeatCommand, { type: BattleCommandEvent }>,
): TransitionResult {
  const { battle } = state;
  if (command.seat !== battle.currentTurn) {
    return reject(ERROR_CODES.NOT_YOUR_TURN);
  }
  const { targets } = command.payload;
  if (command.type === CLIENT_EVENTS.UPDATE_TARGETS) {
    // A draft may hold any count up to the allowance; every other target rule applies as to a shot.
    if (targets.length > shotsAllowed(battle, state.rules)) {
      return reject(ERROR_CODES.INVALID_TARGETS, TARGET_VIOLATIONS.WRONG_TARGET_COUNT);
    }
    const shots = battle.boards[otherSeat(battle.currentTurn)].shots;
    const validation = validateTargets(targets, shots, targets.length);
    if (!validation.ok) {
      return reject(ERROR_CODES.INVALID_TARGETS, validation.reason);
    }
    return accept({ ...state, draftTargets: targets });
  }

  const resolution = resolveTurn(battle, targets, state.rules);
  if (!resolution.ok) {
    return reject(ERROR_CODES.INVALID_TARGETS, resolution.reason);
  }
  const effects: RoomEffect[] = [
    { type: SERVER_EVENTS.SHOT_RESOLVED, payload: { shooter: command.seat, results: resolution.results } },
  ];
  if (resolution.winner !== null) {
    return accept(
      {
        phase: ROOM_PHASES.GAME_OVER,
        roomId: state.roomId,
        rules: state.rules,
        rulesVersion: state.rulesVersion,
        players: state.players,
        battle: resolution.battle,
        winner: resolution.winner,
        reason: GAME_OVER_REASONS.FLEET_DESTROYED,
      },
      effects,
    );
  }
  return accept({ ...state, battle: resolution.battle, draftTargets: [] }, effects);
}

/**
 * Moves a room whose fleets are both confirmed into battle, with empty shot lists and `FIRST_SEAT` to fire.
 * @param state The room in `PLACEMENT`, both fleets confirmed.
 * @returns The room in `IN_PROGRESS`.
 */
function startBattle(state: PlacementRoom): BattleRoom {
  return {
    phase: ROOM_PHASES.IN_PROGRESS,
    roomId: state.roomId,
    rules: state.rules,
    rulesVersion: state.rulesVersion,
    players: state.players,
    battle: {
      boards: {
        P1: { ships: state.fleets.P1.ships, shots: [] },
        P2: { ships: state.fleets.P2.ships, shots: [] },
      },
      currentTurn: FIRST_SEAT,
    },
    draftTargets: [],
  };
}

/**
 * Replaces one seat's placement fleet.
 * @param state The room in `PLACEMENT`.
 * @param seat The seat whose fleet changes.
 * @param fleet The new fleet.
 * @returns A new room; the other seat's fleet is shared, not copied.
 */
function withFleet(state: PlacementRoom, seat: Seat, fleet: PlacementFleet): PlacementRoom {
  return { ...state, fleets: { ...state.fleets, [seat]: fleet } };
}

/**
 * Builds an accepted result.
 * @param state The room after the command.
 * @param effects What the caller must do besides sending `STATE`; none by default.
 * @returns The result.
 */
function accept(state: RoomState, effects: readonly RoomEffect[] = []): AcceptedTransition {
  return { ok: true, state, effects };
}

/**
 * Builds a refused result.
 * @param error The code for the ack.
 * @param violation The rule broken, for `INVALID_PLACEMENT` and `INVALID_TARGETS`.
 * @returns The result.
 */
function reject(error: ErrorCode, violation?: PlacementViolation | TargetViolation): RejectedTransition {
  return violation === undefined ? { ok: false, error } : { ok: false, error, violation };
}

/**
 * The seat across the table.
 * @param seat A seat.
 * @returns The other one.
 */
export function otherSeat(seat: Seat): Seat {
  return seat === SEATS.P1 ? SEATS.P2 : SEATS.P1;
}
